---
title: "Number cracking on output file"
output: pdf_document
date: "2023-05-04"
---
Subset of the output differentiated by diaganosis
```{r}
MEL<-subset(output,Label == "MEL")
NEV<-subset(output, Label == "NEV")
SEK<-subset(output, Label == "SEK")
```




Symmetry:
```{r}
Sym_MLE<-(MEL$Symmetry)
NEV_mean_sym<-mean(MEL$Symmetry)
NEV_sd_sym<-sd(MEL$Symmetry)
```

```{r}
Sym_nev<-(NEV$Symmetry)
NEV_mean_sym<-mean(NEV$Symmetry)
NEV_sd_sym<-sd(NEV$Symmetry)

```


```{r}
Sym_sek<-(SEK$Symmetry)
SEK_mean_sym<-mean(SEK$Symmetry)
SEK_sd_sym<-sd(SEK$Symmetry)


```


```{r}
t.test(Sym_MLE,Sym_nev)
t.test(Sym_sek,Sym_nev)
t.test(Sym_sek,Sym_MLE)
```


## RGB:

# MEL:



Red:
```{r}
Red_MEL<-MEL$MeanRed
Red_MEL_mean<-mean(Red_MEL)
Red_MEL_sd<-sd(Red_MEL)
print(Red_MEL_mean)
print(Red_MEL_sd)
```

Green:
```{r}
Green_MEL<-MEL$MeanGreen
Green_MEL_mean<-mean(Green_MEL)
Green_MEL_sd<-sd(Green_MEL)
print(Green_MEL_mean)
print(Green_MEL_sd)
```



Blue: 
```{r}
Blue_MEL<-MEL$MeanBlue
Blue_MEL_mean<-mean(Blue_MEL)
Blue_MEL_sd<-sd(Blue_MEL)
print(Blue_MEL_mean)
print(Blue_MEL_sd)
```


## NEV

Red
```{r}
Red_NEV<-NEV$MeanRed
Red_NEV_mean<-mean(Red_NEV)
Red_NEV_sd<-sd(Red_NEV)
print(Red_NEV_mean)
print(Red_NEV_sd)
```

Blue
```{r}
Blue_NEV<-NEV$MeanBlue
Blue_NEV_mean<-mean(Blue_NEV)
Blue_NEV_sd<-sd(Blue_NEV)
print(Blue_NEV_mean)
print(Blue_NEV_sd)
```

Green
```{r}
Green_NEV<-NEV$MeanGree
Green_NEV_mean<-mean(Green_NEV)
Green_NEV_sd<-sd(Green_NEV)
print(Green_NEV_mean)
print(Green_NEV_sd)
```

# SEK

Red

```{r}
Red_SEK<-SEK$MeanRed
Red_SEK_mean<-mean(Red_SEK)
Red_SEK_sd<-sd(Red_SEK)
print(Red_SEK_mean)
print(Red_SEK_sd)
```

Blue

```{r}
Blue_SEK<-SEK$MeanBlue
Blue_SEK_mean<-mean(Blue_SEK)
Blue_SEK_sd<-sd(Blue_SEK)
print(Blue_SEK_mean)
print(Blue_SEK_sd)
```

Green

```{r}
Green_SEK<-SEK$MeanGreen
Green_SEK_mean<-mean(Green_SEK)
Green_SEK_sd<-sd(Green_SEK)
print(Green_SEK_mean)
print(Green_SEK_sd)
```
```{r}
mean(SEK$SDGreen)
mean(MEL$SDGreen)
```

```{r}
#Green t.test
t.test(Green_SEK,Green_MEL)
t.test(Green_SEK, Green_NEV)
t.test(Green_NEV,Green_MEL)

#Blue t.test
t.test(Blue_SEK,Blue_MEL)
t.test(Blue_SEK, Blue_NEV)
t.test(Blue_NEV,Blue_MEL)

#Red t.test

t.test(Red_SEK,Red_MEL)
t.test(Red_SEK, Red_NEV)
t.test(Red_NEV,Red_MEL)
```




Compactness


```{r}
Mel_compac<-MEL$Compactness
MEL_mean_compac<-mean(MEL$Compactness)
sd_MEL_Compac<-sd(MEL$Compactness)
print(MEL_mean_compac)
print(sd_MEL_Compac)

```


```{r}
NEV_compac<-NEV$Compactness
NEV_mean_compac<-mean(NEV$Compactness)
sd_NEV_Compac<-sd(NEV$Compactness)
print(NEV_mean_compac)
print(sd_NEV_Compac)
```

```{r}
SEK_compac<-SEK$Compactness
SEK_mean_compac<-mean(SEK$Compactness)
sd_SEK_Compac<-sd(SEK$Compactness)
print(SEK_mean_compac)
print(sd_SEK_Compac)
```

```{r}
t.test(NEV_compac,SEK_compac)
t.test(NEV_compac,Mel_compac)
t.test(Mel_compac,SEK_compac)
```


```{r}
```

